AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FortiGate fgt-guardduty-event - Parse IP from GuardDuty event and
  save it into a S3 bucket file
Parameters:
  Prefix:
    Description: Every resource name will start with this prefix
    Type: String
  BucketName:
    Description: Bucket Name to upload all Python Files
    Type: String
  BucketFileName:
    Description: File name with all IPs
    Type: String
Resources:
  RoleFGT:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 
        Fn::Sub:
        - ${prefix}-Rule-FortiGate-Block-IP
        - prefix:
            Ref: Prefix
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      MaxSessionDuration: 3600
  PolicyFGT:
    Type: AWS::IAM::RolePolicy
    Properties:
      PolicyName: 
        Fn::Sub:
        - ${prefix}_Invoke_Lambda_FortiGate_Block_IP
        - prefix:
            Ref: Prefix
      RoleName:
        Ref: RoleFGT
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - Fn::GetAtt:
                  - ServerLessFunction
                  - Arn 
  ServerLessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      CodeUri: function
      Description: Receive a GuardDuty event
      Timeout: 10
      Environment:
        Variables:
          S3_BUCKET: !Ref BucketName
          S3_BLOCKLIST_KEY: !Ref BucketFileName
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:ListAllMyBuckets
                - s3:GetObject
                - s3:PutObject
              Resource:
                - '*'
      Tracing: Active
      Layers:
        - !Ref libs
      Events:
        EventBridgeRule:
          Type: EventBridgeRule
          Properties:
            RuleName: !Sub
              - ${prefix}-FortiGate-IP-BlockList
              - prefix: !Ref Prefix
            Target:
              Id: FortiGate-IP-BlockList-Target
              Arn: !GetAtt ServerLessFunction.Arn
              RoleArn: !GetAtt RoleFGT.Arn
            Pattern:
              source:
                - aws.guardduty
              detail-type:
                - GuardDuty Finding
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: fortinet-gd-event-python-lib
      Description: Dependencies for the FortiGate fgt-guardduty-event app.
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.13