AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FortiGate fgt-guardduty-event - Parse IP from GuardDuty event and
  save it into a S3 bucket file
Parameters:
  BucketName:
    Description: Bucket Name to upload all Python Files
    Type: String
  BucketFileName:
    Description: File name with all IPs
    Type: String
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      CodeUri: function
      Description: Receive a GuardDuty event
      Timeout: 10
      Environment:
        Variables:
          S3_BUCKET: !Ref BucketName
          S3_BLOCKLIST_KEY: !Ref BucketFileName
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:ListAllMyBuckets
                - s3:GetObject
                - s3:PutObject
              Resource:
                - '*'
      Tracing: Active
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: fortinet-gd-event-python-lib
      Description: Dependencies for the FortiGate fgt-guardduty-event app.
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.13